/** @type {import('@stryker-mutator/core').PartialStrykerOptions} */
export default {
  testRunner: 'vitest',
  vitest: {
    configFile: 'vitest.config.ts',
    related: false,
  },
  mutate: [
    'src/shared/autoCategory.ts',
    'src/shared/categories.ts',
    'src/shared/dateUtils.ts',
    'src/shared/dayStatus.ts',
    'src/shared/holidays.ts',
    'src/shared/periodCategories.ts',
    'src/shared/worktime.ts',
    'src/features/day/confirmDay.ts',
    'src/features/day/dayContext.ts',
    'src/features/day/dayType.ts',
    'src/features/day/dayUpdaters.ts',
    'src/features/day/workPeriodMerge.ts',
    'src/features/month/daySummary.ts',
    'src/features/month/monthStats.ts',
    'src/features/month/overtimeCarryOver.ts',
    'src/features/settings/autoFillRules.ts',
    'src/features/settings/excelMapping.ts',
    'src/features/settings/exportStatus.ts',
    'src/features/sprint/sprint.ts',
    'src/features/sprint/sprintGroups.ts',
    'src/features/table/buildMonthTable.ts',
    'src/features/table/categoryMutations.ts',
    'src/features/excel/excelService.ts',
    'src/features/excel/localExcelService.ts',
    'src/shared/hotkeyConfig.ts',
    'src/shared/undoStore.ts',
  ],
  reporters: ['html', 'clear-text', 'progress'],
  htmlReporter: { fileName: 'reports/mutation/index.html' },
  thresholds: { high: 80, low: 60, break: 50 },
  coverageAnalysis: 'perTest',
  ignoreStatic: true,
  ignorePatterns: ['dist', 'dist-electron', 'reports'],
}
